name: Cypress Tests

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  cypress-e2e:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Run e2e Tests
        run: npx cypress run --spec 'cypress/e2e/' --reporter mochawesome --reporter-options "reportDir=cypress/reports,overwrite=false,html=false,json=true"

      - name: Upload Mochawesome Reports as Artifact
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: mochawesome-reports
          path: cypress/reports/*.json

      - name: Download Mochawesome Reports Artifact
        uses: actions/download-artifact@v4
        with:
          name: mochawesome-reports
          path: cypress/reports/

      - name: Upload ZIP file to Uploadcare
        run: |
          curl -F "UPLOADCARE_PUB_KEY=1e9a01d70860ee491ef0" \
               -F "file=@cypress/reports/mochawesome-reports.zip" \
               -H "Content-Type: multipart/form-data" \
               "https://upload.uploadcare.com/base/"
